// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI tooling (migrate, db pull) must use the DIRECT connection:
    // Prisma's migration engine takes advisory locks and runs DDL that
    // Neon's connection pooler doesn't reliably proxy. The app itself
    // uses the pooled DATABASE_URL at runtime.
    url: process.env["DIRECT_DATABASE_URL"],
  },
});
